Change how building works (faster builds & easier to update)
NopeCHA/NopeCHA pull request #9
Opened 2022-10-10 17:56 UTC by brunoais

2022-10-10 18:17 UTC, brunoais commented on build.py
> +                extension_manifest.update(specific_manifest)
I could put some manifest versioning knowledge in the code here but I thought it would increase the complexity here unecessarily.
The complexity needed would be to delete `browser_action` or `action` as required. However, I can add complexity to, without logic attached, copy `action` to `browser_action`.
But if conditionals about manifest versioning are welcome, then I can add the complexity which allows simplifying the `manifest.base.json` more.

2022-10-10 18:17 UTC, brunoais commented on manifest.base.json
> +    "browser_action": {
I decided going to the simpler option of having this twice. I'm not sure if that's the best option. It depends a LOT on what Jae wants.

Regardless, If wanted, I can add some logic to deal with this duplication

2022-10-10 18:17 UTC, brunoais commented on manifest.base.json
> +    "version": "0.2.0",
This is quite a change, so I thought BUMPing the version would make sense. If there's some other idea for the version, let me know

2022-10-10 18:17 UTC, brunoais commented on manifest.base.json
> +                "*://*.recaptcha.net/recaptcha/*",
This is different from what firefox had but it works on my browser, so I think this can stay with `matches` like this, making it the same for both browsers

2022-10-10 18:17 UTC, brunoais commented on build.py
> +        versions = filter(lambda p: p.is_dir(), VERSIONS_PATH.iterdir())
Even though I'm about sure there shouldn't be any files here, I want to be really sure

2022-10-10 18:17 UTC, brunoais commented on build.py
> +printe = partial(print, file=sys.stderr)
Logging and such goes to stderr.

2022-10-10 18:17 UTC, brunoais commented on build.py
> +with in_dir(dir_path):
I decided that the location of the `build.py` should be where everything is related to. The location it's expected to be at is the root of the project so it should work correctly in most situations

2022-10-10 18:25 UTC, Le0Developer commented on build.py
> +    pass  # Not mandatory
```suggestion
    watchdog = None  # Not mandatory
```
and then check if watchdog is None instead of catching a NameError

2022-10-10 18:25 UTC, Le0Developer commented on build.py
> +except NameError:
```suggestion
if watchdog is None:
```

2022-10-10 18:26 UTC, Le0Developer commented on build.py
> +        exit(2)
```suggestion
if watchdog is None and program_args.watch:
    parser.print_help()
    printe(f"\nERROR: \n {WATCHDOG_NOT_FOUND}\n")
    exit(2)
```

2022-10-10 18:28 UTC, Le0Developer commented on build.py
> +                    extension_manifest = json.load(f)
just personal preference, feel free to ignore
```suggestion
                extension_manifest = json.loads(BASE_MANIFEST.read_text())
```

2022-10-10 18:31 UTC, Le0Developer commented on build.py
> +                    json.dump(extension_manifest, f, indent=4)
personal preference again, also added bonus of not clearing the entire file if the json dump fails for some reason
```suggestion
                manifest_content = json.dumps(extension_manifest, indent=4)
                (export_directory / 'manifest.json').write_text(manifest_content)
```

2022-10-10 18:32 UTC, Le0Developer commented on README.md
> +Having python 3.8 or above installed
```suggestion
Having [Python 3.8](https://python.org) or above installed.
```

2022-10-10 20:53 UTC, brunoais commented
> Also why -d/deploy? I'd consider -p/production to be more intuitive.

Sounds good to me. I'll do that among others tomorrow.

2022-10-10 20:54 UTC, brunoais commented on build.py
> +    pass  # Not mandatory
That is also a valid way. I'll do that.

2022-10-10 20:55 UTC, brunoais commented on build.py
> +                    extension_manifest = json.load(f)
It does look good to me, though. I'm buying it ^^

2022-10-10 20:56 UTC, brunoais commented on build.py
> +                    json.dump(extension_manifest, f, indent=4)
In my opinion this one is arguable... But it is rather valid. I'll think about it tomorrow.

2022-10-11 19:47 UTC, Le0Developer commented on README.md
> +Note: The `-w` is also supported here: (`python build.py -dw`)
`-d` -> `-p`

2022-10-13 16:01 UTC, brunoais commented on manifest.base.json
> +    "version": "0.2.0",
I changed this. Is `0.1.19` correct?

2022-10-13 16:10 UTC, Le0Developer requested changes
Also could you stop force pushing every time and just use commits normally? Impossible to keep track of changes between commits/reviews.

2022-10-13 16:10 UTC, Le0Developer commented on build.py
> +sys.path.append('./pylibs')
```suggestion
```
this does not belong in here

2022-10-13 17:09 UTC, brunoais commented
> Also could you stop force pushing every time and just use commits normally? Impossible to keep track of changes between commits/reviews.

Too much habit from work. I'll do that

2022-10-13 17:16 UTC, brunoais commented on build.py
> +sys.path.append('./pylibs')
I think it does. Otherwise, how will python include watchdog installed as explained in the `README.md`?
Basically we'd have 3 options (while changing `README.md` to explain the new method)

1. Ask the user to change `PYTHONPATH` environment variable globally or on any run
2. Create a venv and tell the user to install and run python using the venv created (either by activating or by using the python executable of the environment

I think those are worse options than just appending that in the code.

2022-10-13 17:20 UTC, brunoais commented
You can still see the differences here:
![image](https://user-images.githubusercontent.com/639467/195663834-598a83c8-b5da-426b-b813-b8c968f7298b.png)

2022-10-13 21:24 UTC, Le0Developer commented on build.py
> +sys.path.append('./pylibs')
Installing python modules locally/globally is prefered.

If the user has conflicts they should be knowledgable enough about python to setup a venv themselves.

2022-10-13 22:23 UTC, Le0Developer requested changes
See earlier comment for `pylibs` changes.

Also please run [black](https://black.readthedocs.io/en/stable/) on `build.py`.

2022-10-13 22:23 UTC, Le0Developer commented on .gitignore
> +/pylibs
```suggestion
```

2022-10-13 22:23 UTC, Le0Developer commented on README.md
> +`python -m pip install -t pylibs watchdog`
```suggestion
For that, you need to install python's `watchdog` in your machine:

`python -m pip install watchdog`
```

2022-10-13 22:23 UTC, Le0Developer commented on README.md
> +Note: The `-w` is also supported here: (`python build.py -pw`)
```suggestion
Note: The watchdog option `-w` is also supported here: (`python build.py -pw`)
```

2022-10-13 22:23 UTC, Le0Developer commented on README.md
> +Minified code for production can be found in the `.zip` files in the corresponding browser directory. The Zip files can be used for final testing/debugging before sending to webstores and are the sam
```suggestion
Minified code for production can be found in the `.zip` files in the corresponding browser directory. The zip files can be used for final testing/debugging before sending them to the webstores.
```
redundant

2022-10-14 07:46 UTC, brunoais commented on README.md
> +Minified code for production can be found in the `.zip` files in the corresponding browser directory. The Zip files can be used for final testing/debugging before sending to webstores and are the sam
That is better wording. Thank you

2022-10-14 08:03 UTC, Le0Developer reviewed
`__export__` -> `dist`

also some path cleanup

2022-10-14 08:03 UTC, Le0Developer commented on build.py
> +                zip_deploy = ZipFile(export_directory / EXTENSION_ZIP_NAME, 'w', ZIP_DEFLATED, compresslevel=9)
```suggestion
                ext = "xpi" if version.basename == "firefox" else "crc"
                zip_deploy = ZipFile(EXPORT_PATH / f"NopeCHA.{ext}", 'w', ZIP_DEFLATED, compresslevel=9)
```
put them in the main `dist` directory with the correct file extension

2022-10-14 08:03 UTC, Le0Developer commented on version/chrome/manifest.json
> +    "background": {"service_worker": "version/chrome/background.js"},
```suggestion
    "background": {"service_worker": "background.js"},
```
this should be relative to the manifest

2022-10-14 08:03 UTC, Le0Developer commented on version/firefox/manifest.json
> +        "scripts": ["version/firefox/background.js"]
```suggestion
        "scripts": ["background.js"]
```

2022-10-14 08:18 UTC, brunoais commented on README.md
> +This will create a `__export__` directory in the project root directory, in which you will find `firefox` and `chrome` directories each one with its version for testing and debugging.
I prefer like this:
```suggestion
This will create a `dist` directory in the project root directory, in which you will find `firefox` and `chrome` directories for debugging purposes. If you use the `-p` argument, each debugging directory will have an additional xpi/crc archive for production usage.
```
What do you think?

2022-10-14 08:20 UTC, brunoais commented on build.py
> +                zip_deploy = ZipFile(export_directory / EXTENSION_ZIP_NAME, 'w', ZIP_DEFLATED, compresslevel=9)
I usually use conversion dictionaries for this, even when there's just 2 expected values. However, I think this is fine.

2022-10-14 08:22 UTC, Le0Developer commented on build.py
> +                for file_to_include in itertools.chain(files_to_include, version_files_to_include):
this also includes the "dummy" `manifest.json` with per-browser settings and put the `background.js` into the wrong directory

2022-10-14 08:23 UTC, brunoais commented on version/chrome/manifest.json
> +    "background": {"service_worker": "version/chrome/background.js"},
Unless you are changing the location of the `background.js` and I missed it, the path I wrote is correct. There's no `background.js` at the root of the directory.

2022-10-14 08:23 UTC, brunoais commented on version/firefox/manifest.json
> +        "scripts": ["version/firefox/background.js"]
Unless you are changing the location of the `background.js` and I missed it, the path I wrote is correct. There's no `background.js` at the root of the directory.

2022-10-14 08:23 UTC, Le0Developer commented on build.py
> +                zip_deploy = ZipFile(export_directory / EXTENSION_ZIP_NAME, 'w', ZIP_DEFLATED, compresslevel=9)
feel free to 🤷

2022-10-14 08:24 UTC, Le0Developer commented on README.md
> +This will create a `__export__` directory in the project root directory, in which you will find `firefox` and `chrome` directories each one with its version for testing and debugging.
sure

2022-10-14 08:26 UTC, brunoais commented on build.py
> +                for file_to_include in itertools.chain(files_to_include, version_files_to_include):
This script is designed to keep the files in the original places. The only exception is `manifest.json` because browsers don't allow it to be anywhere else besides the root directory of the archive or testing directory.

If you want me to change that part of the design, I can change but for me, it makes even more sense when more content is added for the next part.
Regardless, I'm fine with changing that.

2022-10-14 08:28 UTC, Le0Developer commented on build.py
> +                for file_to_include in itertools.chain(files_to_include, version_files_to_include):
The files are only in different places because they depend on the browser - it does not make sense for them to stay in a separate directory when the resulting directory/zip is only for a single browser

2022-10-14 11:21 UTC, brunoais commented on build.py
> +                for file_to_include in itertools.chain(files_to_include, version_files_to_include):
It does simplify automation code but I'll do that change, then. There's no strong reason to keep the way I did

2022-10-14 14:23 UTC, brunoais commented on build.py
> +            export_directory = EXPORT_PATH / version
`.basename` doesn't exist in python, so I used `.name`

2022-10-14 14:30 UTC, brunoais commented
I messed the commit order when I tried to merge logically. I hope it's not a problem.
All is here. Just the code between the commits are not well split

2022-10-14 14:32 UTC, Le0Developer reviewed
`deploy` -> `build`

Also please run black.

2022-10-14 14:32 UTC, Le0Developer commented on README.md
> +## Build for deployment
```suggestion
## Building for production
```

2022-10-14 14:32 UTC, Le0Developer commented on build.py
> +    def deploy():
```suggestion
    def build():
```

2022-10-14 14:32 UTC, Le0Developer commented on build.py
> +    deploy()
```suggestion
    build()
```

2022-10-14 14:32 UTC, Le0Developer commented on build.py
> +                    printe("updated")
```suggestion
                    build()
                    printe("changes detected - rebuilt extension")
```
bit more verbose, better UX

2022-10-14 14:46 UTC, brunoais commented
> Also please run black.

There are some things I disagree that the way black with default settings reformatted file is more readable but the result is still rather readable, so I'm fine with that.

2022-10-14 15:30 UTC, brunoais commented on build.py
> +                    exported_file = export_directory / file_to_include.name
This is incorrectly flattening the icons directory.
I need to fix this!

2022-10-14 15:34 UTC, Le0Developer commented on build.py
> +                    EXTENSION_SUFFIXES[version]
```suggestion
                    EXTENSION_SUFFIXES[version.name]
```

2022-10-14 15:37 UTC, Le0Developer commented on build.py
> +                        file_to_include.link_to(exported_file)
This is causing deprecation warnings on python 3.10
```py
NopeCHA/build.py:138: DeprecationWarning: pathlib.Path.link_to() is deprecated and is scheduled for removal in Python 3.12. Use pathlib.Path.hardlink_to() instead.
  file_to_include.link_to(exported_file)
```
not sure if we should,
1. bump min version to 3.10 and switch to `hardlink_to`
2. check python version and choose depending on the current one
3. ignore it

2022-10-14 15:52 UTC, brunoais commented on build.py
> +                        file_to_include.link_to(exported_file)
Seriously?!?! They are making breaking changes on `3.12` O_O?!?!?!
I'll check their discussions

2022-10-14 16:54 UTC, brunoais commented on build.py
> +                        file_to_include.link_to(exported_file)
Ok. a PEP slipped through. In my opinion, the best option is actually a polyfill.
If there's no `hardlink_to` add it.

2022-10-14 16:59 UTC, brunoais commented on build.py
> +                    EXTENSION_SUFFIXES[version]
Ups... Nice catch (I wonder how it worked on my test)

2022-10-14 18:27 UTC, Le0Developer commented on build.py
> +                extension_archive = export_directory / OUTPUT_ARCHIVE_NAME.with_suffix(
```suggestion
                extension_archive = EXPORT_PATH / OUTPUT_ARCHIVE_NAME.with_suffix(
```
easier to find if its in the main dir imo

2022-10-14 18:31 UTC, brunoais commented on build.py
> +                extension_archive = export_directory / OUTPUT_ARCHIVE_NAME.with_suffix(
I don't know which one I prefer, so I'll do that.

2022-10-14 19:19 UTC, Le0Developer approved these changes

2022-10-15 12:12 UTC, merged